---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: goon-auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: goon-auth
    spec:
      containers:
        - image: gcr.io/goonswarm-1303/goon-auth:b8e3a4e
          imagePullPolicy: Always
          name: goon-auth
          ports:
            - containerPort: 4000
          volumeMounts:
            - name: goon-auth-secret
              mountPath: /etc/goon_auth
      volumes:
        - name: goon-auth-secret
          secret:
            secretName: goon-auth-secret
