---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ejabberd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ejabberd
    spec:
      containers:
        - image: gcr.io/goonswarm-1303/ejabberd
          imagePullPolicy: Always
          name: ejabberd
          ports:
            - containerPort: 5222
              name: xmpp
            - containerPort: 5280
              name: ejabberd-http
          volumeMounts:
            - name: tendollarbond-com-tls
              mountPath: /etc/ssl/ejabberd
            - name: ejabberd-config
              mountPath: /etc/ejabberd
            - name: ejabberd-storage
              mountPath: /var/lib/ejabberd
      volumes:
        - name: ejabberd-config
          configMap:
            name: ejabberd-config
        - name: tendollarbond-com-tls
          secret:
            secretName: tendollarbond-com-tls
        - name: ejabberd-storage
          gcePersistentDisk:
            pdName: ejabberd-storage
            fsType: ext4
