---
apiVersion: v1
kind: Service
metadata:
  name: ejabberd
  labels:
    app: ejabberd
spec:
  selector:
    app: ejabberd
  ports:
    - port: 5222
      name: xmpp-c2s
    - port: 5269
      name: xmpp-s2s
    - port: 5280
      name: xmpp-http
