---
apiVersion: v1
kind: ReplicationController
metadata:
  name: ejabberd
  labels:
    app: ejabberd
    spec: v1
spec:
  replicas: 1
  selector:
    app: ejabberd
    spec: v1
  template:
    metadata:
      labels:
        app: ejabberd
        spec: v1
    spec:
      containers:
        - image: gcr.io/goonswarm-1303/ejabberd
          imagePullPolicy: Always
          name: ejabberd
          ports:
            - containerPort: 5222
              name: xmpp
            - containerPort: 5280
              name: ejabberd-http
          volumeMounts:
            - name: k8s-tendollarbond-com-tls
              mountPath: /etc/ssl/ejabberd
            - name: ejabberd-config
              mountPath: /etc/ejabberd
      volumes:
        - name: ejabberd-config
          configMap:
            name: ejabberd-config
        - name: k8s-tendollarbond-com-tls
          secret:
            secretName: k8s-tendollarbond-com-tls
