apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitit
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gitit
    spec:
      containers:
        - image: gcr.io/goonswarm-1303/gitit:ef8cb17
          name: gitit
          resources:
            requests:
              cpu: 30m
