---
apiVersion: v1
kind: ReplicationController
metadata:
  name: forum
  labels:
    app: forum
    spec: v2
spec:
  replicas: 1
  selector:
    app: goon-forum
    spec: v2
  template:
    metadata:
      labels:
        app: goon-forum
        spec: v2
    spec:
      containers:
        - image: mariadb:10.1.13
          imagePullPolicy: Always
          name: mariadb
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mariadb-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: forum-conf
                  key: mariadb.password
        - image: gcr.io/goonswarm-1303/phpbb3
          imagePullPolicy: Always
          name: phpbb3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: phpbb-storage
              mountPath: /var/www/html
      volumes:
        - name: mariadb-storage
          gcePersistentDisk:
            pdName: mariadb-storage
            fsType: ext4
        - name: phpbb-storage
          gcePersistentDisk:
            pdName: phpbb-storage
            fsType: ext4
