---
apiVersion: v1
kind: ReplicationController
metadata:
  name: rocket-chat
  labels:
    app: rocket-chat
    spec: v1
spec:
  replicas: 1
  selector:
    app: rocket-chat
    spec: v1
  template:
    metadata:
      labels:
        app: rocket-chat
        spec: v1
    spec:
      containers:
        - image: rocket.chat:0.31.0
          name: rocket-chat
          env:
            - name: MONGO_URL
              value: mongodb://localhost:27017/meteor
        - image: mongo:3.0
          name: rocket-db
          volumeMounts:
            - name: rocket-storage
              mountPath: /data/db
      volumes:
        - name: rocket-storage
          gcePersistentDisk:
            pdName: rocket-storage
            fsType: ext4
