---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 104.196.134.49
  selector:
    lb-target: nginx
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
    - port: 64738
      name: mumble
    - port: 5222
      name: xmpp-c2s
    - port: 5269
      name: xmpp-s2s
