---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        lb-target: nginx
    spec:
      containers:
        - image: nginx:1.9.12
          name: nginx
          volumeMounts:
            - name: rocket-tendollarbond-com-tls
              mountPath: /etc/nginx/ssl/rocket.tendollarbond.com
            - name: k8s-tendollarbond-com-tls
              mountPath: /etc/nginx/ssl/k8s.tendollarbond.com
            - name: tendollarbond-com-tls
              mountPath: /etc/nginx/ssl/tendollarbond.com
            - name: nginx-dhparam
              mountPath: /etc/nginx/ssl/dhparam
            - name: nginx-config
              mountPath: /etc/nginx/conf
            - name: nginx-logs
              mountPath: /var/log/nginx
          command:
            - '/usr/sbin/nginx'
            - '-c'
            - '/etc/nginx/conf/main.conf'
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 50m
        - image: reactivehub/google-fluentd-catch-all
          name: google-log-agent
          resources:
            requests:
              cpu: 50m
          volumeMounts:
            - name: nginx-logs
              mountPath: /var/log/nginx
      volumes:
        - name: k8s-tendollarbond-com-tls
          secret:
            secretName: k8s-tendollarbond-com-tls
        - name: rocket-tendollarbond-com-tls
          secret:
            secretName: rocket-tendollarbond-com-tls
        - name: tendollarbond-com-tls
          secret:
            secretName: tendollarbond-com-tls
        - name: nginx-dhparam
          secret:
            secretName: nginx-dhparam
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-logs
          emptyDir: {}
