---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 104.196.134.49
  selector:
    lb-target: nginx
  ports:
    - port: 80
      name: http
    - port: 443
      name: https
