---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bads
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: goon-ldap
    spec:
      containers:
        - image: gcr.io/goonswarm-1303/slapd
          imagePullPolicy: Always
          name: goon-ldap
          ports:
            - containerPort: 389
          volumeMounts:
            - name: slapd-storage
              mountPath: /var/lib/openldap/openldap-data
      volumes:
        - name: slapd-storage
          gcePersistentDisk:
            pdName: ldap-storage
            fsType: ext4
