---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bads
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bads
    spec:
      containers:
        - image: gcr.io/goonswarm-1303/bads:c1c0de5
          imagePullPolicy: Always
          name: bads
          env:
            - name: MARIADB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: bads-config
                  key: mariadb.password
