---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kaiwa
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kaiwa
    spec:
      containers:
        - image: gcr.io/goonswarm-1303/kaiwa
          imagePullPolicy: Always
          name: kaiwa
          env:
            - name: NODE_ENV
              value: dev
            - name: KAIWA_SECRET
              valueFrom:
                configMapKeyRef:
                  name: kaiwa-config
                  key: secret
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 25m
            limits:
              memory: 100Mi
